### ISSUE TITLE
confusion about usage

### ISSUE THREAD

**Issue by AvianY** [AndreyG/libgit2cpp#11]
I am not exactly sure how this library wrapper was meant to be used. I am looking at examples and they are okay, but functionalities for cloning and fetching are not there and I actually need them. There is no function for cloning in wrapper, so I was wondering, what kind of role does the wrapper have in relation to the original library?

**Comment by AndreyG** [comment]
It's my hobby project, it doesn't have any official relation to https://libgit2.org.
From time to time I add missing functionality or, if you do it by yourself and make a pull request, I'll merge it with pleasure. It's quite easy, see, for instance, #10 merged recently.
