### ISSUE TITLE
libgit2cpp seems to use deprecated objects

### ISSUE THREAD

**Issue by t-sas** [AndreyG/libgit2cpp#12]
I could not compile the library on windows 10 / VS2017 because git_ref_t and git_otype were not found.

I included todays checkout of libgit2 into libs/libgit2 directory.

both types were found in libgit2's srcdir within include/git2/deprecated.h replaced by:
#define git_ref_t git_reference_t
#define git_otype git_object_t

seems to be deprecated at least since Jan 23rd regarding to libgit2 log

libgit2cpp was compiling fine with my changes appended
[deprecated_patch.txt](https://github.com/AndreyG/libgit2cpp/files/3557252/deprecated_patch.txt)

**Comment by AndreyG** [comment]
@t-sas thank you! I have fixed the issue by the commit 5ce59c2.
