### ISSUE TITLE
How to fetch?

### ISSUE THREAD

**Issue by bewagner** [AndreyG/libgit2cpp#13]
Hi, I'm using your library and like it very much. However I couldn't find an example of how to do `git fetch`.

Is this functionality already included?

**Comment by AndreyG** [comment]
Hi, I have just made initial implementation (d290f4436b4067387343bdc00f20a069103103d2), let me know if some needed for you functionality is missing. PRs are very welcome also!

**Comment by bewagner** [comment]
Thank you very much for your fast response! 
I'll see if that works for me ;-)
