### ISSUE TITLE
Example to create branch

### ISSUE THREAD

**Issue by YLiLarry** [AndreyG/libgit2cpp#5]
I looked into the source code and didn't find a way to create branches and tags.
Can you add an example for creating branches?

**Comment by AndreyG** [comment]
I have added `Repository::create_branch` (fb5f99bf508c6ac6e7382c696114d960439b3093). example of using can be found [here](https://github.com/AndreyG/libgit2cpp/blob/fb5f99bf508c6ac6e7382c696114d960439b3093/examples/branch.cpp).
