### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by AvianY** [AndreyG/libgit2cpp#6]
The simple instructions to building lead me to this error:

`libgit2cpp/src/annotated_commit.cpp:14:16: error: ‘git_annotated_commit_ref’ was not declared in this scope
         return git_annotated_commit_ref(ptr());
`

what am I doing wrong?

**Comment by AndreyG** [comment]
Can you please elaborate, do you use a bundled libgit2 or system? What is your operating system?

**Comment by AvianY** [comment]
what do you mean by which one do I use? I cloned this repo and followed instructions.
I am using debian buster

**Comment by AvianY** [comment]
I looked around and noticed, that debian buster uses libgit which doesn't include commit https://github.com/libgit2/libgit2/commit/698b44639e499b23d882f8a26f3ca5fd4d94f22e and therefore doesn't have that function defined. Possibly missing other things as well, but that's how it is.

**Comment by AndreyG** [comment]
Ok, you can use Cmake option `BUNDLE_LIBGIT2`, it should fix the problem.
